//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTaxiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conductor
    {
        public conductor()
        {
            this.viaje = new HashSet<viaje>();
        }
    
        public int idConductor { get; set; }
        public string nombre { get; set; }
        public string licencia { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> puntuacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idTransporte { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual transporte transporte { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<viaje> viaje { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
