//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTaxiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion
    {
        public int idCotizacion { get; set; }
        public Nullable<int> idUusario { get; set; }
        public Nullable<decimal> Origen { get; set; }
        public Nullable<decimal> Destino { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idTipoTransporte { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual transporte transporte { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
