//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTaxiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public int idPermiso { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idRol { get; set; }
        public string objeto { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
