//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTaxiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recorrido
    {
        public int IdPunto { get; set; }
        public Nullable<int> idViaje { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public Nullable<int> correlativo { get; set; }
    
        public virtual viaje viaje { get; set; }
    }
}
