//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTaxiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public roles()
        {
            this.usuario = new HashSet<usuario>();
            this.permisos = new HashSet<permisos>();
        }
    
        public int idRol { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual ICollection<permisos> permisos { get; set; }
    }
}
