//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTaxiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoTransporte
    {
        public tipoTransporte()
        {
            this.transporte = new HashSet<transporte>();
        }
    
        public int idTipoTransporte { get; set; }
        public string nombre { get; set; }
        public Nullable<int> tarifa { get; set; }
    
        public virtual ICollection<transporte> transporte { get; set; }
    }
}
