//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTaxiV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.conductor = new HashSet<conductor>();
            this.transporte = new HashSet<transporte>();
            this.cotizacion = new HashSet<cotizacion>();
            this.viaje = new HashSet<viaje>();
        }
    
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string correo { get; set; }
        public string sexo { get; set; }
        public Nullable<int> idTipoUsuario { get; set; }
        public string clave { get; set; }
        public Nullable<int> idRol { get; set; }
        public string telefono { get; set; }
        public Nullable<int> idEstado { get; set; }
        public string foto { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string numeroDocumento { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual ICollection<conductor> conductor { get; set; }
        public virtual roles roles { get; set; }
        public virtual ICollection<transporte> transporte { get; set; }
        public virtual ICollection<cotizacion> cotizacion { get; set; }
        public virtual ICollection<viaje> viaje { get; set; }
    }
}
